### ISSUE TITLE
API code no longer seems to work

### ISSUE THREAD

**Issue by wengzilla** [Tenderly/integration-samples#1]
https://github.com/Tenderly/integration-samples/blob/9a040e16aab74807d62bf78e11c0efd86a4858d2/playround-enviroment-for-dapps/src/web3/tenderly.ts

I continue to get 404s when I follow the `deleteFork` example... Has the API changed at all?

**Comment by lokera666** [comment]
a8514e0e331475d66a24db59cdf7f828c3cbcb18
Try that one

**Comment by wengzilla** [comment]
This was resolved by the team in June! Thanks so much for updating.
